### ISSUE TITLE
.m4a / AAC podcast RSS feeds not paginated

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-publisher#1189]
### Expected behavior
Setting an episode limit for a podcast feed should result in a paged RSS feed if the number of published episodes is greater than the set limit. This should apply to all podcast RSS feeds of any given file type.

### Actual behavior
This doesn't seem to happen for .m4a / AAC feeds.

### Further information
I found and [shortly discussed this](https://twitter.com/Inrumpo/status/1344641455831326720) with @timpritlove a while back without knowing what's going on.

Now I did some research and compared the following podcast RSS feeds from a different podcast:

- AAC: `https://pcr.apple.com/id911593013` / `https://fotophonie.de/?feed=m4a`
- MP3: `https://fotophonie.de/?feed=mp3`
- Ogg Vorbis: `https://fotophonie.de/?feed=ogg`
- Opus: `https://fotophonie.de/?feed=opus`

The .m4a / AAC feed is the only one that does not show pages.

**Comment by eteubert** [comment]
I checked for the linked Twitter thread. The Freak Show feed is configured for 30 episodes and this  feed links to a second page which is https://freakshow.fm/feed/m4a?paged=2 and looks fine.

https://fotophonie.de/?feed=m4a does not contain pages because it contains all episodes. It's probably configured that way in Podlove Publisher.

I don't see a Publisher bug here, everything is working as expected as far as I can see.

**Comment by Inrumpo** [comment]
Thanks for your insight. Maybe there are just a few coincidences coming together, leading me to a wrong conclusion. I'll do more research and report back.

**Comment by Inrumpo** [comment]
There has been a coincidence (no feed limit for this one feed and maybe some kind of Pocket Casts bug). Thanks for your efforts!
