### ISSUE TITLE
How to disable gzip compression?

### ISSUE THREAD

**Issue by 343max** [podlove/podlove-publisher#277]
How can I disable gzip compression manually? I have the suspicion pod loves gzip compression is not working that well with W3 Total Cache.

**Comment by funkenstrahlen** [comment]
I think I am running in a similar problem when I activate Zencache:

https://sendegate.de/t/probleme-mit-zencache/1514/4

Feedvalidator says `Not a gzipped file (Server response declares Content-Encoding: gzip; misconfigured server?)`

This error also occurs when I disable rss feed caching in Zencache.

**Comment by eteubert** [comment]
Does [applying the same correction](https://github.com/podlove/podlove-publisher/issues/277#issuecomment-31618304) also fix it?

**Comment by funkenstrahlen** [comment]
You wrote

> add this snippet somewhere to disable gzip

Can you tell me where?

**Comment by funkenstrahlen** [comment]
I added the line to `wp-settings.php`. After clearing Zencache the feed validates now via feedvalidator. It also is served from the cache as expected.

However there is one problem left. The output is no longer gzip compressed. Nor the main page or the feed are compressed. Despite I enabled it in `.htaccess`

```
# Enable gzip compression
<IfModule deflate_module>
    <IfModule filter_module>
        AddOutputFilterByType DEFLATE text/plain text/html
        AddOutputFilterByType DEFLATE text/xml application/xml application/xhtml+xml application/xml-dtd
        AddOutputFilterByType DEFLATE application/rdf+xml application/rss+xml application/atom+xml image/svg+xml
        AddOutputFilterByType DEFLATE text/css text/javascript application/javascript application/x-javascript
        AddOutputFilterByType DEFLATE font/otf font/opentype application/font-otf application/x-font-otf
        AddOutputFilterByType DEFLATE font/ttf font/truetype application/font-ttf application/x-font-ttf
    </IfModule>
</IfModule>
```

Do you know why?

**Comment by funkenstrahlen** [comment]
Fixed it. I did not enable gzip compression correctly on uberspace. Now it seems to work. Thank you.

**Comment by funkenstrahlen** [comment]
Why do you even do gzip in podlove? shouldn't you leave this to the webserver?

**Comment by eteubert** [comment]
> Why do you even do gzip in podlove? shouldn't you leave this to the webserver?

Because the size/performance of feeds/feed requests is crucial to server performance. I don't expect users to fiddle with htaccess rules to enable a fundamental feature (their server not going down once an episode is released).

If some software caches a site and then delivers it with the wrong headers (like caching a gzipped site and then delivering it with html or plain text headers) I consider this a bug in the caching layer. But I'm not sure what exactly the issue in your stack was.

We *do* check if the server is actually able to do gzip compression and if the client accepts it. But if the zlib-module is available to PHP but not to your web server, there might be issues. I don't think we can check for those edge cases though.
