### ISSUE TITLE
Blog posts & Podcasts are mixed in the .../podcast/ page

### ISSUE THREAD

**Issue by GoetzMueller** [podlove/podlove-publisher#633]
Maybe I've got it wrong but I thought the .../podcast/ page (defined via the expert settings) should only list the podcasts (ie. custom post types 'podcast') but it also shows standard blog posts.

**Comment by eteubert** [comment]
I assume your theme is to blame again.
To check, you can activate one of the standard themes for a moment and see if it works as expected there.

**Comment by GoetzMueller** [comment]
I wouldn't be surprised ;-) However, I had also assumed that the podcast page is only existing due to the plugin. The issue is probably that no one apart the plugin is able to know what to include and what to exclude, even to know what to deal with. And the plugin can't know how the page design itself should look like. I guess I'll "build" my own based on the episode list shortcode.

**Comment by eteubert** [comment]
The problem is that your theme hooks very deep into WordPress. I am using the proper WordPress API and specifically tell it to only use the podcast post type. Your theme overrides it deep inside the query stack. So even if you build your own, you need to find the filter the theme is using and override it deliberately after the theme sets its post types.
