### ISSUE TITLE
Sitemap.xml with Yoast's WordPress SEO plugin

### ISSUE THREAD

**Issue by pgerstbach** [podlove/podlove-publisher#639]
Hi,

I use Yoast's WordPress SEO plugin that includes a sitemap generator. It seems to have an issue with episodes, there is only one generic entry "/podcast/%pagename%/" but not for each episode. Is this an issue with podlove publisher or with the SEO plugin?

Here is an example: http://businessanalysepodcast.de/podcast-sitemap.xml

Thanks,
Peter

**Comment by eteubert** [comment]
Thanks, I can see the issue but I'm not sure yet which plugin should fix it.

@gglnx I traced it a bit. Yoast correctly uses `get_permalink($post)` to retrieve the url: https://github.com/Yoast/wordpress-seo/blob/trunk/inc/class-sitemaps.php#L759
The resulting url, however, is `http://local.wordpress.dev/%pagename%/`. Now I wonder why it's _page_ name in the first place, not _post_ name.
If you remember, the publisher fiddles with the permalinks quite a bit. Here's the file: https://github.com/podlove/podlove-publisher/blob/release-2-0/includes/permalinks.php But all that code is only concerned with `%postname%`. Which, I feel, is correct because we only deal with posts, not pages ... any insights?

**Comment by gglnx** [comment]
Will be fixed with Publisher 2.0 :)

**Comment by pgerstbach** [comment]
Thanks, works great now!
