### ISSUE TITLE
Feature Request: Access contributor list via contributor settings

### ISSUE THREAD

**Issue by jonasschoen** [podlove/podlove-publisher#650]
I think for Podlove beginners it is unusual to look for the contributors list under episodes --> contributors. At first many of them (just like me) search for the list under Podlove --> Contributor settings and don't find any hint to the actual place. Just like [some users wrote at Sendegate](https://sendegate.de/t/contributors-verwalten/340/3). I suggest to add a Link to it or a hint to the contributor settings.

**Comment by eteubert** [comment]
Yep, I'm aware that this is hard to find.
We placed it there because it feels more like "content" than "configuration" but we received enough confused questions to convince us that doesn't matter. Nobody looks for it there.

I actually want something like this in every contributor dropdown:
![screen_shot_2015-02-12_at_13_22_23](https://cloud.githubusercontent.com/assets/235918/6162230/7456cdbe-b2ba-11e4-86e3-28be7a4a38f2.png)

Because then it doesn't really matter where in the menu structure it is. The "add new" just takes you there whenever you want to add a new one.
