### ISSUE TITLE
Episode Stats not shown in Dashboard and in list view

### ISSUE THREAD

**Issue by Nefariuscipher** [podlove/podlove-publisher#694]
Hey there!

I have uploaded 3 episodes and they work correctly. However the duration and length of the file is always shown as 0. How can I solve this?

**Comment by timpritlove** [comment]
Please share some URLs here. We can't test this without any references. Which site? Which files? What do you do and what do you expect where?

**Comment by Nefariuscipher** [comment]
Yeah sometimes I forget the obvious things ;-)

It contains MP3 files and I have successfully created 3 episodes which are played in the browser. Nevertheless the Dashboard of Podlove shows always 00:00:00 

The URL is www.schuledermacher.com 
The Problem is, the files are within a membership site plugin. I would need to give you access to that first. Attached there is a screenshot.
![bildschirmfoto 2015-03-10 um 18 16 32](https://cloud.githubusercontent.com/assets/11409562/6580540/a4dcbdee-c751-11e4-8e9b-ca403ac92432.png)

**Comment by eteubert** [comment]
Your files must be publicly available, otherwise the Publisher can't access them.
If you want to protect your podcast, the only way right now is via the feed. Disable discoverability in each feed and only list episodes and display subscription information behind the paywall.

It's not perfect since anybody can share the feed information, but that's the best you can do right now.

If each of your members has his own WordPress account, you can also use the feed protection feature:

![screen shot 2015-03-11 at 13 30 04](https://cloud.githubusercontent.com/assets/235918/6590865/d7661a02-c7f2-11e4-8b3e-675fcfc93f9c.png)

Keep in mind, though, that this makes subscribing for your users much more complicated and many clients don't support authenticated feeds.
