### ISSUE TITLE
Fatal error: Call to undefined function Podlove\Settings\filter_input()

### ISSUE THREAD

**Issue by optikfluffel** [podlove/podlove-publisher#844]
Hi, on a newly setup Wordpress `4.5.1` running on PHP `5.6.20` behind an Nginx I get a blank screen after activating the plugin. When enabling Wordpress' debug stuff I get:

```
Fatal error: Call to undefined function Podlove\Settings\filter_input() in /www/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/settings/settings.php on line 29
```

You know what I missed setting this up?

Thanks upfront!

**Comment by eteubert** [comment]
Strange. The [`filter_input()` function](https://secure.php.net/manual/en/function.filter-input.php) exists since PHP 5.2. 

If you have access to the php.ini or phpinfo(), see if the function is listed under the [`disable_functions` directive](https://secure.php.net/manual/en/ini.core.php#ini.disable-functions) (although I wouldn't know why it would be listed there).

**Comment by eteubert** [comment]
On second thought, it's more likely that the PHP ["filter" extension](https://secure.php.net/manual/en/book.filter.php) is not enabled. Please verify/enable it and try again.

**Comment by optikfluffel** [comment]
I recompile PHP and now everything seems fine 😁
