### ISSUE TITLE
Itunes will not show new cover art

### ISSUE THREAD

**Issue by tasovi** [podlove/podlove-publisher#851]
Hi, 
I changed the cover image of the podcast. The feed has the correct url to the image, that I uploaded in WP and selected in podlove.
But iTunes won't update it.
it has the size 1400x1400x and less than 200kb
What is wrong? 

thx

**Comment by timpritlove** [comment]
I guess you are referring to <http://pendler-podcast.de/feed/mp3/>. It does include an 1400x1400px image so everything is fine. iTunes might need some time (up to days) reflecting this due to irregular refresh times.

Again, this is not a support forum so please direct further questions to https://community.podlove.org/
