### ISSUE TITLE
Analytics hour of day

### ISSUE THREAD

**Issue by bread-on-toast** [podlove/podlove-publisher#925]
It would be nice to see when there is rush-hour at my podcast. Can the analytics tool show me the distribuition over the time of day?
Something like:

0-1:00 n downloads
1:2:00 m downloads
...

**Comment by eteubert** [comment]
This wouldn't be a useful statistics. Due to the nature of podcast clients, the most active hours will always be those following an episode release. It may make some sense if you exclude all automated downloads and only look at webplayer statistics. But even this is most likely skewed by the rate and time of your episode publications.

I'm closing this since we try to keep this platform for bug reports only. For discussion please head over to community.podlove.org.
