### ISSUE TITLE
Database entries in VxUtG_podlove_downloadintentclean missing

### ISSUE THREAD

**Issue by juekr** [podlove/podlove-publisher#926]
### Expected behavior
Earlier today, the analytics section showed somewhat around 1.900 downloads over all of our podcast episodes. 

### Actual behavior
Comparing an older backup file (this morning) with a current database dump (a few minutes old) shows: the newer file has ~280 less rows in the table VxUtG_podlove_downloadintentclean. 

### System information (see `Podlove > Support` menu)
Website             http://das-a.ch
PHP Version         7.0.14-nmm1
WordPress Version   4.7.4
WordPress Theme     Mon Cahier Child v1.0.0
Publisher Version   2.5.2
Web Player Version  2.1.1
Twig Version        1.32.0
open_basedir        ok
curl Version        7.35.0
iconv               available
simplexml           ok
max_execution_time  30
upload_max_filesize 200M
memory_limit        256M
disable_classes     
disable_functions   
permalinks          ok (/%postname%/)
podlove_permalinks  ok
podcast_settings    ok
web_player          ok
podlove_cache       on
assets              
  - mp3    audio/mpeg http://das-a.ch/feed/mp3/
  - m4a    audio/mp4  http://das-a.ch/feed/m4a/
cron                ok

0 errors
0 notices
Nice, Everything looks fine!

**Comment by eteubert** [comment]
Is it possible you used the "Download Intent Cleanup" Tool manually? Because the automatic hourly job only aggregates _new_ data, but when you start it via the tools page, it calculates everything from scratch.

Now, deduplication works better when looking at the whole dataset at once, which means that you may seem to lose some downloads. However, running "Download Intent Cleanup" should always result in the same numbers.

I can't say for sure if that's what happened but it's my best guess for now :)

**Comment by juekr** [comment]
Thanks for getting back to me about that. No, to my knowledge nobody triggered a manual cleanup. 

So does that mean that if I don't do manual cleanups from time to time, my numbers actually get way too high?

Cheers,
Jürgen

**Comment by eteubert** [comment]
> So does that mean that if I don't do manual cleanups from time to time, my numbers actually get way too high?

They _may_ be higher but not significantly. I consider this a bug and hope I will find a way around this some day.

**Comment by juekr** [comment]
Okay, thanks for the insights!
