### ISSUE TITLE
Multisite Network features issues

### ISSUE THREAD

**Issue by cfoellmann** [podlove/podlove-publisher#995]
### Expected behavior
Activate publisher on page 1 of a multisite (multisite.tld/wp-admin/plugins.php).
Show network-wide settings on network admin (multisite.tld/network/admin.php?page=podlove_network_settings_handle)

### Actual behavior
Menu + settings pages are not added to network admin.

You need to activate `network-wide` but you might not want the publisher to be active on all sites. e.g. you might have a site for the blog which does not need the weight of the publisher.

### System information (see `Podlove > Support` menu)
```
Website                    http://site2.wp-cloud.test
PHP Version                7.2.5-1+ubuntu14.04.1+deb.sury.org+1
WordPress Version          4.9.8
WordPress Theme            Twenty Seventeen v1.7
Active Plugins             
           - Podlove Podcast Publisher v2.7.11
           - Yoast SEO Premium v7.8
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.7.11
Web Player Version         player_v4
Twig Version               1.35.3
open_basedir               ok
curl Version               7.35.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        1024M
memory_limit               256M
disable_classes            
disable_functions          pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,
permalinks                 ok (/%year%/%monthnum%/%day%/%postname%/)
podlove_permalinks         ok
podcast_settings           Dein Podcast benötigt einen Titel.
web_player                 ok
podlove_cache              on
assets                     
  - mp3    audio/mpeg       http://site2.wp-cloud.test/feed/mp3/
cron                       ok
multisite                  ok

1 FEHLER: 
- Dein Podcast benötigt einen Titel.
0 notices
````

**Comment by cfoellmann** [comment]
This starts with https://github.com/podlove/podlove-publisher/blob/192a2710b6ad3d0f5eff67f4daacb5d6dac6ab4a/lib/modules/networks/networks.php#L24-L27
But a change for my proposal/issue is not as easy as removing just that. I am not familiar with the codebase so someone else needs to comment on this

**Comment by eteubert** [comment]
My grudge with WordPress here is that blog with id `1` is treated specially and from a user's perspective that does not make sense. No one without WordPress development knowledge would expect this behavior. 

If you have podcasts on blog 3, 7 and 10, you probably also want to use the network screen. As long as Podove Publisher plugin is activated on more than one blog, no matter which ones, network functionality should be there. If I recall correctly (it's been a while since the network module was written) that is not possible because blog 1 is used for network code, so if Podlove Publisher is not active on blog 1, it can't display network screens.

My suggestion: replace the line above with a filter based return:

```php
$active = is_plugin_active_for_network( basename(\Podlove\PLUGIN_DIR) . '/' . \Podlove\PLUGIN_FILE_NAME );
if ( ! apply_filters('podlove_network_module_activate', $active ) ) {
  return;
}
```

That way site admins can force activate the network module if they know what they're doing but end users can't stumble upon unexpected behavior.

**Comment by cfoellmann** [comment]
You are totally right. Plugins for the network-admin are only available if active on blog `1`.
